week5/moma-app/config/routes.rb
Rails.application.routes.draw do

  # CREATE
  get "/artists/new" => "artists#new"
  post "/artists" => "artists#create"

  # READ
  get "/artists" => "artists#index"
  get "/artists/:id" => "artists#show", as: 'artist'

  # UPDATE
  get "/artists/:id/edit" => "artists#edit", as: 'artist_edit'

  patch "/artists/:id" => "artists#update"

  # DELETE
  delete "/artists/:id" => "artists#destroy", as: 'artist_delete'


  # Works CRUD routes
  resources :works


end

week5/moma-app/app/models/artist.rb
class Artist < ApplicationRecord
  has_many :works
end

week5/moma-app/app/models/work.rb
class Work < ApplicationRecord
  belongs_to :artist  # mandatory association by default!! 
end

week5/moma-app/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  # CREATE ##########################################
  def new
    @artist = Artist.new
  end

  def create

    # use 'strong params' to filter the fields from the form (for security reasons)
    Artist.create( artist_params )

    # Artist.create(
    #   name: params[:artist][:name],
    #   nationality: params[:artist][:nationality],
    # )

    redirect_to( artists_path )  # redirect to the index

  end

  # READ ############################################
  def index
    @artists = Artist.all # returns an array of Artist objects
  end

  def show
    @artist = Artist.find params[:id] # returns one Artist object
  end

  # UPDATE ##################################################

  def edit
    @artist = Artist.find params[:id]
  end

  def update
    @artist = Artist.find params[:id]
    @artist.update artist_params

    redirect_to artist_path(@artist.id)
  end

  # DESTROY ########################################
  def destroy
    artist = Artist.find params[:id]
    artist.destroy

    redirect_to( artists_path )  # index page
  end

  private

  def artist_params
    # This method ensures that the 'artist' key is set in the params hash, and then
    # makes sure only the permitted columns are taken from the form (and saved to the database)
    params.require(:artist).permit( :name, :nationality, :dob, :period, :roundness, :bio, :image )
  end

end

week5/moma-app/app/controllers/works_controller.rb
class WorksController < ApplicationController

  # CREATE
  def new
    @work = Work.new   # create a blank object for the form_for helper to use
  end

  def create
    Work.create work_params  # pass in the strong version of the form params
    redirect_to( works_path )  # redirect to the index "/works"
  end

  # READ
  def index
    @works = Work.all
  end

  def show
    @work = Work.find params[:id]  # ID is in params because of the route "/works/:id"
  end

  # UPDATE
  def edit
    @work = Work.find params[:id]
  end

  def update
    @work = Work.find params[:id]   # route is PATCH "/works/:id", so we have the ID in params
    @work.update work_params
    redirect_to work_path(@work.id)
  end

  # DESTROY
  def destroy
    @work = Work.find params[:id]
    @work.destroy
    redirect_to( works_path )
  end

  private

  def work_params
    params.require(:work).permit(:title, :year, :medium, :style, :image, :artist_id)
  end


end

week5/moma-app/app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
  <fieldset>
    <%= f.label :name %><!-- gives us a <label> tag -->
    <%= f.text_field :name %> <!-- gives us <input type="text" name="name"> -->
  </fieldset>
  <fieldset>
    <%= f.label :nationality %>
    <%= f.text_field :nationality %>
  </fieldset>
  <fieldset>
    <%= f.label :dob, 'Date of Birth' %>
    <%= f.text_field :dob %>
  </fieldset>
  <fieldset>
    <%= f.label :period %>
    <%= f.text_field :period %>
  </fieldset>
  <fieldset>
    <%= f.label :roundness %>
    <%= f.text_field :roundness %>
  </fieldset>
  <fieldset>
    <%= f.label :bio %>
    <%= f.text_field :bio %>
  </fieldset>
  <fieldset>
    <%= f.label :image, 'Image URL'  %>
    <%= f.text_field :image%>
  </fieldset>

  <%= f.submit %>

<% end %>

week5/moma-app/app/views/artists/edit.html.erb
<h2>Edit <%= @artist.name %></h2>

<%= render partial: 'form' %>

week5/moma-app/app/views/artists/index.html.erb
<h2>All Artists</h2>

<ul>
<% @artists.each do |artist| %>
  <li>
    <a href="<%= artist_path(artist.id) %>">
      <%= artist.name  %>, (<%= artist.nationality %>)
    </a>
  </li>
<% end %>
</ul>

week5/moma-app/app/views/artists/new.html.erb
<h2>Add New Artist</h2>

<%= render partial: 'form' %>

week5/moma-app/app/views/artists/show.html.erb
<h2><%= @artist.name %></h2>

<div>
  <%= link_to 'Edit This Artist', artist_edit_path(@artist) %>
  |
  <%= link_to 'Delete This Artist', artist_delete_path(@artist), method: 'delete' %>
</div>
<br>


<strong>Nationality:</strong> <%= @artist.nationality %><br>
<strong>Date of Birth:</strong> <%= @artist.dob %><br>
<strong>Period:</strong> <%= @artist.period %><br>
<strong>Roundness:</strong> <%= @artist.roundness %><br>
<strong>Biography:</strong> <%= @artist.bio %><br>

<h4>Works:</h4>
<ul>
<% @artist.works.each do |work| %>
  <li>
    <%= link_to work.title, work_path(work.id) %>, <%= work.year.year %>
  </li>
<% end %>
</ul>

<%= image_tag @artist.image, alt: @artist.name, class: 'artistPortait' %>

week5/moma-app/app/views/works/_form.html.erb
<%= form_for @work do |f| %>
  <fieldset>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </fieldset>
  <fieldset>
    <%= f.label :year %>
    <%= f.text_field :year %>
  </fieldset>
  <fieldset>
    <%= f.label :medium %>
    <%= f.text_field :medium %>
  </fieldset>
  <fieldset>
    <%= f.label :style %>
    <%= f.text_field :style %>
  </fieldset>
  <fieldset>
    <%= f.label :image %>
    <%= f.text_field :image %>
  </fieldset>
  <fieldset>
    <%= f.label :artist_id, 'Artist' %>
    <%= f.collection_select :artist_id, Artist.all, :id, :name, prompt: 'Please choose the artist' %>
  </fieldset>

  <%= f.submit %>

<% end %>

week5/moma-app/app/views/works/edit.html.erb
<h2>Edit <em><%= @work.title %></em></h2>

<%= render partial: 'form' %>

week5/moma-app/app/views/works/index.html.erb
<h2>Works Index</h2>

<ul>
<% @works.each do |work| %>
  <li>
    <%= link_to work.title, work_path(work.id) %>, <%= work.year.year %>
  </li>
<% end %>
</ul>

week5/moma-app/app/views/works/new.html.erb
<h2>Add New Work</h2>

<%= render partial: 'form' %>

week5/moma-app/app/views/works/show.html.erb
<h2><em><%= @work.title %></em>, <%= @work.year.year %></h2>
<strong><%= link_to @work.artist.name, artist_path(@work.artist.id) %></strong>


<p>Medium: <%= @work.medium %></p>
<p>Style: <%= @work.style %></p>

<%= image_tag @work.image, alt: @work.title, class: 'artworkImage' %>

<br>

<%= link_to 'Edit This Work', edit_work_path(@work) %>
|
<%= link_to 'Delete This Work', work_path(@work), method: 'delete' %>