week5/planets-db/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Planets CRUD routes

  # CREATE: blank form & form submit action
  get "/planets/new" => "planets#new"
  post "/planets"    => "planets#create"

  # READ: index & show
  get "/planets" => "planets#index"
  get "/planets/:id" => "planets#show", as: 'planet'

  # UPDATE: prefilled form & form submit action
  get "/planets/:id/edit" => "planets#edit", as: 'planet_edit'
  post "/planets/:id"     => "planets#update"

  # DELETE
  get "/planets/:id/delete" => "planets#destroy", as: 'planet_destroy'

end

week5/planets-db/app/models/planet.rb
class Planet < ApplicationRecord # Inherit behaviour from ActiveRecord
end

week5/planets-db/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

  skip_before_action :verify_authenticity_token, raise: false

  # CREATE part 1: blank form
  def new
  end

  # CREATE part 2: form submit here, to create item
  def create

    Planet.create(
      name: params[:name],
      image: params[:image],
      orbit: params[:orbit],
      diameter: params[:diameter],
      mass: params[:mass],
      temperature: params[:temperature],
      moons: params[:moons]
    )

    # CREATE has no template of its own:
    # redirect to index page
    redirect_to( planets_path )

  end

  # READ type 1: index of all items in 'planets'
  def index
    # Get all rows in the planets table
    # (as an array of Planet objects)
    @planets = Planet.all
  end

  # READ type 2: show page, details for one item. whose ID we know
  def show
    # Gets us one row, and returns it as an object
    # (an instance of the Planet model class)
    @planet = Planet.find params[:id]
  end

  # UPDATE part 1: show the prefilled edit form
  def edit
    @planet = Planet.find params[:id]
  end

  # UPDATE part 2: form submit to here,
  # update item in database and redirect to show page
  def update
    planet = Planet.find params[:id]
    planet.update(
      name: params[:name],
      image: params[:image],
      orbit: params[:orbit],
      diameter: params[:diameter],
      mass: params[:mass],
      temperature: params[:temperature],
      moons: params[:moons]
    )

    # redirect to the show page for the planet we just updated
    redirect_to( planet_path(planet.id) )
  end

  # DELETE: remove the item from the table
  def destroy
    planet = Planet.find params[:id]
    planet.destroy

    redirect_to( planets_path )
  end


end

week5/planets-db/app/views/planets/edit.html.erb
<h2>Edit Planet: <%= @planet.name %></h2>

<form action="<%= planet_path(@planet.id) %>" method="post">
Name: <input type="text" name="name" value="<%= @planet.name %>"><br/>
Image URL: <input type="text" name="image" value="<%= @planet.image %>"><br/>
Orbit: <input type="text" name="orbit" value="<%= @planet.orbit %>"><br/>
Diameter: <input type="text" name="diameter" value="<%= @planet.diameter %>"><br/>
Mass: <input type="text" name="mass" value="<%= @planet.mass %>"><br/>
Temperature: <input type="text" name="temperature" value="<%= @planet.temperature %>"><br/>
Moons: <input type="text" name="moons" value="<%= @planet.moons %>"><br/>
<br>
<input type="submit" value="Update">


</form>

week5/planets-db/app/views/planets/index.html.erb
<h2>Index of Planets</h2>

<ul>
<% @planets.each do |planet| %>
  <li>
    <!-- use the 'path helper' to generate the correct url for the show page for planets, passing in the ID of the planet we want to show -->
    <a href="<%= planet_path(planet.id) %>">
      <%= planet.name %>
    </a>
  </li>
<% end %>
</ul>

week5/planets-db/app/views/planets/new.html.erb
<h2>Create New Planet</h2>

<form action="<%= planets_path %>" method="post">
Name: <input type="text" name="name"><br/>
Image URL: <input type="text" name="image"><br/>
Orbit: <input type="text" name="orbit"><br/>
Diameter: <input type="text" name="diameter"><br/>
Mass: <input type="text" name="mass"><br/>
Temperature: <input type="text" name="temperature"><br/>
Moons: <input type="text" name="moons"><br/>
<br>
<input type="submit" value="Create">


</form>

week5/planets-db/app/views/planets/show.html.erb
<h2>Planet <%= @planet.name %></h2>

<!--
<a href="<%= planet_destroy_path(@planet.id) %>">Destroy this Planet</a> -->

<%= link_to 'Edit this Planet', planet_edit_path(@planet.id) %>
|
<%= link_to 'Destroy this Planet', planet_destroy_path(@planet.id), class: 'destroy', id: 'delete_link' %>

<p><strong>Orbit:</strong> <%= @planet.orbit %> earth orbits</p>
<p><strong>Diameter:</strong> <%= @planet.diameter %> earth diameters</p>
<p><strong>Mass:</strong> <%= @planet.mass %> earth masses </p>
<p><strong>Temperature:</strong> <%= @planet.temperature %> earth temp </p>
<p><strong>Moons:</strong> <%= @planet.moons %></p>

<!-- make sure the image field is non-nil and .length > 0 -->
<% if @planet.image.present? %>
  <!-- <img src="<%= @planet.image %>" alt="<%= @planet.name %>"> -->
  <%= image_tag @planet.image, alt: @planet.name, class: 'planet'  %>
<% end %>