week5/tunr-db-wdi29/config/routes.rb
Rails.application.routes.draw do



  resources :users, except: [ :index ]  # don't create the index action or template

  # Session routes for login/logut
  get    "/login" => "session#new"     # login form
  post   "/login" => "session#create"  # form submits here to perform login and set session
  delete "/login" => "session#destroy" # logout (delete session)

  resources :mixtapes

end

week5/tunr-db-wdi29/app/models/album.rb
class Album < ApplicationRecord
  has_many :songs

  # this is weird: it seems like it should be that an album 'belongs_to' an artist,
  # but because this is an association through 'songs', and an album has many
  # songs, it's also has_many to get from the album to the artist(s)
  has_many :artists, through: 'songs'

  def artist
      # self is the keyword to talk about "the current object", i.e.:
      # al = Album.first
      # al.artist   # 'self' will be the object 'al'
      self.artists.uniq
  end


end

week5/tunr-db-wdi29/app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  has_many :albums, through: 'songs'  # a through association: get to the albums of an artist via their songs, and from the other end: get the artist and album belongs to via the songs
  has_many :genres, through: 'songs'
end

week5/tunr-db-wdi29/app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :songs # many-to-many association with songs

  has_many :artists, through: 'songs'
end

week5/tunr-db-wdi29/app/models/mixtape.rb
class Mixtape < ApplicationRecord
  has_and_belongs_to_many :songs
  belongs_to :user, optional: true

  validates :name, presence: true, length: {minimum: 4}
end

week5/tunr-db-wdi29/app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist, optional: true
  belongs_to :album, optional: true
  has_and_belongs_to_many :genres # many-to-many association with genres
  has_and_belongs_to_many :mixtapes
end

week5/tunr-db-wdi29/app/models/user.rb
class User < ApplicationRecord

  # Encrypt the 'password' field for this model, and save the encrypted
  # string in the 'password_digest' column
  # (requires the 'bcrypt' gem)
  has_secure_password   # makes 'password' field MANDATORY

  has_many :mixtapes

  validates :email, presence: true, uniqueness: true

end

week5/tunr-db-wdi29/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Our fetch_user method will be run before ANY action of ANY controller
  # (because ApplicationController is the parent class of all of them)
  before_action :fetch_user

  private

  def check_if_logged_in
    unless @current_user.present?
      flash[:error] = "You must be logged in to view that page."
      redirect_to login_path

    end
  end

  def fetch_user
    # Check if session[:user_id] is set, and also if it stores
    # a valid user ID, and if so, set an instance variable
    # containing the user object

    if session[:user_id].present?
      @current_user = User.find_by id: session[:user_id]
    end

    # Make sure we actually found a valid user (i.e. the user ID in
    # the session wasn't stale, from a deleted account)
    # and if we didn't get a valid user (in @current_user)
    # then we clear the session key
    session[:user_id] = nil unless @current_user.present?
  end

end

week5/tunr-db-wdi29/app/controllers/mixtapes_controller.rb
class MixtapesController < ApplicationController

  # Run the check_if_logged_in method in application_controller.rb
  # which redirects users to the login page if they are not logged
  # in - they need to be logged in to create and edit mixtapes
  # (because mixtapes belong_to users)
  # BUT they don't have to login to browse the mixtapes,
  # i.e. index and show actions
  before_action :check_if_logged_in, except: [:index, :show]

  def new
    @mixtape = Mixtape.new
  end

  def create
    # Multi-step way to create a new Mixtape record in the database
    # for when we have to add some data that is not in the submitted
    # form (i.e., the user ID from the currently logged-in user):
    # First make a .new object, set the extra field, then .save

    @mixtape = Mixtape.new( mixtape_params )  # strong params
    @mixtape.user = @current_user
    # could also write: mixtape.user_id = @current_user.id
    @mixtape.save
    # OR: @mixtape = @current_user.mixtapes.create mixtape_params

    if @mixtape.persisted?
      redirect_to mixtapes_path # redirect to index
    else
      # @mixtape did not get saved to the DB

      flash[:errors] = @mixtape.errors.full_messages # an array of error strings we can print
      # redirect_to new_mixtape_path

      # Render a *different* action's template (new instead of create)
      # We do this so the form can be pre-populated with the values typed
      # in by the user when they submitted it the first time
      render :new
    end


  end

  def index
    @mixtapes = Mixtape.all
  end

  def show
    @mixtape = Mixtape.find params[:id]  # key comes from /mixtapes/:id
  end

  def edit
    @mixtape = Mixtape.find params[:id]  # key comes from /mixtapes/:id
  end

  def update
    @mixtape = Mixtape.find params[:id]  # key comes from /mixtapes/:id

    # Check that the owner of this mixtape is STILL the logged-in user
    # (i.e. the ID in the edit form action was not tampered with)
    unless @mixtape.user == @current_user
      redirect_to(mixtapes_path) # this alone does not stop the action
      return  # stop the rest of the action from running! i.e. the update below
    end

    # check whether the update actually changed the DB or not
    # (.update returns true if it did change the DB, false if there was an error)
    if @mixtape.update( mixtape_params )
      # successfully updated the DB
      redirect_to mixtape_path(@mixtape) # redirect to show page
    else
      # error updating
      flash[:errors] = @mixtape.errors.full_messages
      render :edit   # Render the edit template to show the form, even though this is the update action
    end

  end # update

  def destroy
    mixtape = Mixtape.find params[:id]  # key comes from /mixtapes/:id
    mixtape.destroy
    redirect_to mixtapes_path
  end

  private
  def mixtape_params
    params.require(:mixtape).permit(:name, :image)
  end

end # class

week5/tunr-db-wdi29/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    # see if the email address entered actually corresponds to a user in the table
    user = User.find_by email: params[:email]

    if user.present? && user.authenticate( params[:password] )
      # Successful login:
      # Get Rails to create a new session key to store the user's ID;
      # this is the session key which we will use to check if the user
      # is logged in on all future pages
      session[:user_id] = user.id
      redirect_to user_path( user.id )
    else
      # Bad credentials, i.e. unsuccessful login

      # Set a flash message which exists *just for the next page load*
      flash[:error] = "Invalid email address or password"

      redirect_to( login_path )
    end

  end

  def destroy
    session[:user_id] = nil  # this logs out the user
    redirect_to login_path
  end
end

week5/tunr-db-wdi29/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.create user_params   # strong params

    if user.persisted?
      # Account created successfully!
      session[:user_id] = user.id   # Log in the new user!!
      redirect_to user_path(user)   # go to the show page for this user
    else
      # Account not created: show error

      # Set a flash key to show on the next page: it will be an array of error strings
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path  # /users/new, show the form again (with errors)
    end


  end

  def show
    # raise '🌴'
    # console
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  # strong params, the doorman for the form fields
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

week5/tunr-db-wdi29/app/helpers/mixtapes_helper.rb
module MixtapesHelper
end

week5/tunr-db-wdi29/app/helpers/session_helper.rb
module SessionHelper
end

week5/tunr-db-wdi29/app/helpers/users_helper.rb
module UsersHelper
end

week5/tunr-db-wdi29/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TunrDbWdi29</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <h1>Tunr</h1>
    <nav>
      <% if @current_user.present? %>
        Welcome, <%= @current_user.name %>
        |
        <%= link_to 'Logout', login_path, method: 'delete' %>
      <% else %>
        <%= link_to 'Login', login_path %>
        |
        <%= link_to 'Sign up', new_user_path %>
      <% end %>
    </nav>
    <hr>

    <%= yield %>
  </body>
</html>

week5/tunr-db-wdi29/app/views/mixtapes/_form.html.erb
<% if flash[:errors].present? %>
<strong>Please correct the following errors in the form:</strong>
<ol>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
</ol>
<% end %>

<%= form_for @mixtape do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <br>
  <%= f.submit %>

<% end %>

week5/tunr-db-wdi29/app/views/mixtapes/create.html.erb
<h1>Mixtapes#create</h1>
<p>Find me in app/views/mixtapes/create.html.erb</p>

week5/tunr-db-wdi29/app/views/mixtapes/destroy.html.erb
<h1>Mixtapes#destroy</h1>
<p>Find me in app/views/mixtapes/destroy.html.erb</p>

week5/tunr-db-wdi29/app/views/mixtapes/edit.html.erb
<h2>Edit <%= @mixtape.name %></h2>

<%= render partial: 'form' %>

week5/tunr-db-wdi29/app/views/mixtapes/index.html.erb
<h2>All Mixtapes</h2>

<ul>
  <% @mixtapes.each do |mixtape| %>
    <li>
      <%= link_to mixtape.name, mixtape_path(mixtape.id) %> 
      (<%= mixtape.user.name %>)
    </li>
  <% end %>
</ul>

week5/tunr-db-wdi29/app/views/mixtapes/new.html.erb
<h2>Create a Mixtape</h2>

<%= render partial: 'form' %>

week5/tunr-db-wdi29/app/views/mixtapes/show.html.erb
<h2><%= @mixtape.name %></h2>

Created by <%= @mixtape.user.name %>
<br>
<% if @mixtape.image.present? %>
  <%= image_tag @mixtape.image, class: 'mixtapeCover' %>
<% end %>
<br>

<!--
   Only show the edit link if the user who created the current
   mixtape *is* the currently logged-in user, i.e.:
   1. is someone logged in?
   2. is that someone the same person as the owner of the mixtape?
 -->
<% if @current_user.present? && @mixtape.user == @current_user %>
  <%= link_to 'Edit Mixtape', edit_mixtape_path(@mixtape)  %>
<% end %>

week5/tunr-db-wdi29/app/views/mixtapes/update.html.erb
<h1>Mixtapes#update</h1>
<p>Find me in app/views/mixtapes/update.html.erb</p>

week5/tunr-db-wdi29/app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

week5/tunr-db-wdi29/app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

week5/tunr-db-wdi29/app/views/session/new.html.erb
<h2>Login</h2>

<% if flash[:error] %>
  <br>
  <strong><%= flash[:error] %></strong>
  <br><br>
<% end %>


<%= form_tag login_path do %>

  <%= label_tag :email %>
  <%= email_field_tag :email, nil %>
  <br>
  <%= label_tag :password %>
  <%= password_field_tag :password, nil %>
  <br>
  <%= submit_tag 'Login' %>

<% end %>

week5/tunr-db-wdi29/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

week5/tunr-db-wdi29/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

week5/tunr-db-wdi29/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

week5/tunr-db-wdi29/app/views/users/new.html.erb
<h2>Create an Account</h2>

<% if flash[:errors].present?  %>
   <strong>Please correct the following errors:</strong>
   <ol>
   <% flash[:errors].each do |error| %>
     <li><%= error %></li>
   <% end %>
   </ol>
<% end %>

<%= form_for @user do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>

  <%= f.submit %>

<% end %>

week5/tunr-db-wdi29/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

week5/tunr-db-wdi29/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>